name: Publish to npm using np

on:
  push:
    branches:    
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Publish to npm
        run: npx np patch
        with:
          NPM_AUTH_TOKEN: "{{ secrets.NPM_AUTH_TOKEN }}"
