name: Run Node-tap tests

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install modules
        run: npm ci

      - name: Run node-tap tests
        run: npm test
